plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.gradle.userdev' version '7.0.190'
}

tasks.named('wrapper', Wrapper).configure {
    gradleVersion = '8.14.3'
    distributionType = Wrapper.DistributionType.BIN
}

version = mod_version
group = 'dev.redy1aye.copperequipment'

base {
    archivesName = 'CopperEquipment-NeoForge-' + minecraft_version
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

println "Java: ${System.getProperty 'java.version'}, JVM: ${System.getProperty 'java.vm.version'} (${System.getProperty 'java.vendor'}), Arch: ${System.getProperty 'os.arch'}"

runs {
    configureEach {
        systemProperty 'forge.logging.markers', 'REGISTRIES'
        systemProperty 'forge.logging.console.level', 'debug'
        modSource project.sourceSets.main
        if (project.hasProperty('forge_force_ansi')) {
            jvmArgument "-Dterminal.ansi=${project.property('forge_force_ansi')}"
        }
        if (project.javaToolchains.launcherFor(java.toolchain).map { it.metadata.vendor }.getOrElse("").contains("JetBrains")) {
            jvmArgument "-XX:+AllowEnhancedClassRedefinition"
        }
    }
    client {
        runType 'client'
        systemProperty 'neoforge.enabledGameTestNamespaces', 'copperequipment'
        if (project.hasProperty('mc_uuid')) {
            arguments '--uuid', project.property('mc_uuid')
        }
        if (project.hasProperty('mc_username')) {
            arguments '--username', project.property('mc_username')
        }
        if (project.hasProperty('mc_accessToken')) {
            arguments '--accessToken', project.property('mc_accessToken')
        }
    }
    server {
        runType 'server'
        systemProperty 'neoforge.enabledGameTestNamespaces', 'copperequipment'
        arguments '--nogui'
    }
    gameTestServer {
        runType 'gameTestServer'
        systemProperty 'neoforge.enabledGameTestNamespaces', 'copperequipment'
    }
    data {
        runType 'data'
        arguments.addAll '--mod', 'copperequipment', '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

repositories {
    mavenCentral()
    maven { url 'https://maven.neoforged.net/releases' }
}

dependencies {
    implementation "net.neoforged:neoforge:20.6.137"
}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
        minecraft_version: minecraft_version,
        minecraft_version_range: minecraft_version_range,
        neo_version: neo_version,
        loader_version_range: loader_version_range,
        mod_id: 'copperequipment',
        mod_name: 'Copper Equipment',
        mod_license: 'MIT',
        mod_version: mod_version,
        mod_authors: 'redy1aye',
        mod_description: 'Enjoy your copper armor and tools!'
    ]
    inputs.properties replaceProperties
    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}

tasks.named('jar', Jar).configure {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
    manifest.attributes([
        'Specification-Title': 'copperequipment',
        'Specification-Vendor': 'redy1aye',
        'Specification-Version': '1',
        'Implementation-Title': project.name,
        'Implementation-Version': project.jar.archiveVersion,
        'Implementation-Vendor': 'redy1aye',
        'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
    ])
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/mcmodsrepo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}