modLoader="javafml"
loaderVersion="${loader_version}"
license="MIT"

[[mods]]
modId="copperequipment"
version="${mod_version}"
displayName="Copper Equipment"
logoFile="copperequipment-forge-logo.png"
authors="Redy1aye"
description="Enjoy your copper armor and tools!"

[[dependencies.copperequipment]]
    modId="neoforge"
    mandatory=true
    versionRange="${neo_version}"
    ordering="NONE"
    side="BOTH"

[[dependencies.copperequipment]]
    modId="minecraft"
    mandatory=true
    versionRange="${mc_version}"
    ordering="NONE"
    side="BOTH"