modLoader="javafml"
loaderVersion="${loader_version_range}"
license="MIT"
[[mods]]
    modId="copperequipment"
version="${mod_version}"
    displayName="Copper Equipment"
	logoFile="copperequipment-neoforge-logo.png"
    authors="redy1aye"
    description="Enjoy your copper armor and tools!"
[[dependencies.copperequipment]]
    modId="neoforge"
    mandatory=true
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"
[[dependencies.copperequipment]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"